### ISSUE TITLE
Getting value error on basic initializing code

### ISSUE THREAD

**Issue by misingnoglic** [michaelhelmick/python-tumblpy#34]
Hi, when I try to run this basic code, I get this error:
ValueError: Only unicode objects are escapable. Got <generator object <genexpr> at 0x1056301e0> of type <type 'generator'>.

What could be the issue? My code is below:

from tumblpy import Tumblpy
from secrets import tumblr_oauth_key , tumblr_secret_key, tumblr_token, tumblr_token_secret

t = Tumblpy(tumblr_token, tumblr_token_secret, tumblr_oauth_key, tumblr_secret_key)
blog_url = t.post('user/info')

**Comment by misingnoglic** [comment]
Here is the entire traceback: 

/usr/local/bin/python /Users/arya/PycharmProjects/tumblr-snapr/upload_test.py
Traceback (most recent call last):
  File "/Users/arya/PycharmProjects/tumblr-snapr/upload_test.py", line 10, in <module>
    blog_url = t.post('user/info')
  File "/usr/local/lib/python2.7/site-packages/tumblpy/api.py", line 182, in post
    extra_endpoints=extra_endpoints, params=params)
  File "/usr/local/lib/python2.7/site-packages/tumblpy/api.py", line 136, in request
    response = func(url, **kwargs)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 447, in request
    prep = self.prepare_request(req)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 378, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/models.py", line 307, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/models.py", line 494, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python2.7/site-packages/requests_oauthlib/oauth1_auth.py", line 79, in __call__
    unicode(r.url), unicode(r.method), r.body or '', r.headers)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 304, in sign
    ('oauth_signature', self.get_oauth_signature(request)))
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 131, in get_oauth_signature
    uri, headers, body = self._render(request)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 203, in _render
    request.oauth_params, request.headers, realm=realm)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/utils.py", line 31, in wrapper
    return target(params, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/parameters.py", line 57, in prepare_headers
    escaped_value = utils.escape(value)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/utils.py", line 56, in escape
    'Got %s of type %s.' % (u, type(u)))
ValueError: Only unicode objects are escapable. Got <generator object <genexpr> at 0x1056301e0> of type <type 'generator'>.

Process finished with exit code 1

**Comment by misingnoglic** [comment]
Wait this is a dumb error please ignore
