### ISSUE TITLE
TumblpyError: Unable to decode authorized tokens

### ISSUE THREAD

**Issue by snarfed** [michaelhelmick/python-tumblpy#52]
Saw this for the first time today. No changes to tumblpy since 2017, not sure if it's stable and mature or unmaintained (or both), but filing here anyway to share details. `oauth_token` and `oauth_verifier` look ok, and oddly when the user reloaded a second later with the exact same params, it worked fine, ie didn't error. Odd.

tumblpy 1.1.4, Python 3.11, on Google App Engine.

```
Traceback (most recent call last):
...
  File "oauth_dropins/tumblr.py", line 117, in dispatch_request
    auth_token = tp.get_authorized_tokens(verifier)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tumblpy/api.py", line 95, in get_authorized_tokens
    raise TumblpyError('Unable to decode authorized tokens.')
tumblpy.exceptions.TumblpyError: Unable to decode authorized tokens.
```

**Comment by snarfed** [comment]
Oh, this is probably due to a transient error from tumblr.com itself. Looks like this happens when a response from their token URL is blank:

https://github.com/michaelhelmick/python-tumblpy/blob/21490bd6cd03d159a440b2c13a6b4641c789c954/tumblpy/api.py#L83-L97
